import { OrderType } from "@/types";
import React from "react";
import DataTable from "./tableContainer/DataTable";
import {
  orderColumns,
  emailFilter,
  dateRangeFilter,
} from "./tableColumns/OrderColumns";

const OrdersTable = () => {
  const fakeOrders: OrderType[] = [
    {
      _id: "aohfiacqwpoj",
      orderCode: "#alwifxls",
      customer: { _id: "lascvoauvc", fullName: "ali", email: "ali@gmail.com" },
      createdAt: "2023-10-01T12:00:00Z",
      total: 125.22,
      subtotal: 130.22,
      tax: 5.22,
      status: "completed",
      products: [],
    },
    {
      _id: "aohalllcqwpoj",
      orderCode: "#lwstdnf",
      customer: { _id: "ahsyfmrn", fullName: "ahad", email: "ahad@gmail.com" },
      createdAt: "2023-10-15T12:00:00Z",
      total: 110.5,
      subtotal: 115.5,
      tax: 5,
      status: "pending",
      products: [],
    },
    {
      _id: "lwpanncfdx",
      orderCode: "#hafswzqq",
      customer: { _id: "mmxsfww", fullName: "amir", email: "amir@gmail.com" },
      createdAt: "2023-10-08T12:00:00Z",
      total: 98.9,
      subtotal: 100.0,
      tax: 2.1,
      status: "cancelled",
      products: [],
    },
    {
      _id: "poidyyys",
      orderCode: "#xxmztsd",
      customer: { _id: "llaeqcfds", fullName: "ali", email: "ali@gmail.com" },
      createdAt: "2023-10-19T12:00:00Z",
      total: 95.0,
      subtotal: 107.5,
      tax: 12.5,
      status: "shipping",
      products: [],
    },
    {
      _id: "aohfiacqwpoj",
      orderCode: "#alwifxls",
      customer: { _id: "lascvoauvc", fullName: "ali", email: "ali@gmail.com" },
      createdAt: "2023-10-01T12:00:00Z",
      total: 125.22,
      subtotal: 130.22,
      tax: 5.22,
      status: "completed",
      products: [],
    },
    {
      _id: "aohalllcqwpoj",
      orderCode: "#lwstdnf",
      customer: { _id: "ahsyfmrn", fullName: "ahad", email: "ahad@gmail.com" },
      createdAt: "2023-10-15T12:00:00Z",
      total: 110.5,
      subtotal: 115.5,
      tax: 5,
      status: "pending",
      products: [],
    },
    {
      _id: "lwpanncfdx",
      orderCode: "#hafswzqq",
      customer: { _id: "mmxsfww", fullName: "amir", email: "amir@gmail.com" },
      createdAt: "2023-10-08T12:00:00Z",
      total: 98.9,
      subtotal: 100.0,
      tax: 2.1,
      status: "cancelled",
      products: [],
    },
    {
      _id: "poidyyys",
      orderCode: "#xxmztsd",
      customer: { _id: "llaeqcfds", fullName: "ali", email: "ali@gmail.com" },
      createdAt: "2023-10-19T12:00:00Z",
      total: 95.0,
      subtotal: 107.5,
      tax: 12.5,
      status: "shipping",
      products: [],
    },
    {
      _id: "aohfiacqwpoj",
      orderCode: "#alwifxls",
      customer: { _id: "lascvoauvc", fullName: "ali", email: "ali@gmail.com" },
      createdAt: "2023-10-01T12:00:00Z",
      total: 125.22,
      subtotal: 130.22,
      tax: 5.22,
      status: "completed",
      products: [],
    },
    {
      _id: "aohalllcqwpoj",
      orderCode: "#lwstdnf",
      customer: { _id: "ahsyfmrn", fullName: "ahad", email: "ahad@gmail.com" },
      createdAt: "2023-10-15T12:00:00Z",
      total: 110.5,
      subtotal: 115.5,
      tax: 5,
      status: "pending",
      products: [],
    },
    {
      _id: "lwpanncfdx",
      orderCode: "#hafswzqq",
      customer: { _id: "mmxsfww", fullName: "amir", email: "amir@gmail.com" },
      createdAt: "2023-10-08T12:00:00Z",
      total: 98.9,
      subtotal: 100.0,
      tax: 2.1,
      status: "cancelled",
      products: [],
    },
    {
      _id: "poidyyys",
      orderCode: "#xxmztsd",
      customer: { _id: "llaeqcfds", fullName: "ali", email: "ali@gmail.com" },
      createdAt: "2023-10-19T12:00:00Z",
      total: 95.0,
      subtotal: 107.5,
      tax: 12.5,
      status: "shipping",
      products: [],
    },
    {
      _id: "aohfiacqwpoj",
      orderCode: "#alwifxls",
      customer: { _id: "lascvoauvc", fullName: "ali", email: "ali@gmail.com" },
      createdAt: "2023-10-01T12:00:00Z",
      total: 125.22,
      subtotal: 130.22,
      tax: 5.22,
      status: "completed",
      products: [],
    },
    {
      _id: "aohalllcqwpoj",
      orderCode: "#lwstdnf",
      customer: { _id: "ahsyfmrn", fullName: "ahad", email: "ahad@gmail.com" },
      createdAt: "2023-10-15T12:00:00Z",
      total: 110.5,
      subtotal: 115.5,
      tax: 5,
      status: "pending",
      products: [],
    },
    {
      _id: "lwpanncfdx",
      orderCode: "#hafswzqq",
      customer: { _id: "mmxsfww", fullName: "amir", email: "amir@gmail.com" },
      createdAt: "2023-10-08T12:00:00Z",
      total: 98.9,
      subtotal: 100.0,
      tax: 2.1,
      status: "cancelled",
      products: [],
    },
    {
      _id: "poidyyys",
      orderCode: "#xxmztsd",
      customer: { _id: "llaeqcfds", fullName: "ali", email: "ali@gmail.com" },
      createdAt: "2023-10-19T12:00:00Z",
      total: 95.0,
      subtotal: 107.5,
      tax: 12.5,
      status: "shipping",
      products: [],
    },
    {
      _id: "aohfiacqwpoj",
      orderCode: "#alwifxls",
      customer: { _id: "lascvoauvc", fullName: "ali", email: "ali@gmail.com" },
      createdAt: "2023-10-01T12:00:00Z",
      total: 125.22,
      subtotal: 130.22,
      tax: 5.22,
      status: "completed",
      products: [],
    },
    {
      _id: "aohalllcqwpoj",
      orderCode: "#lwstdnf",
      customer: { _id: "ahsyfmrn", fullName: "ahad", email: "ahad@gmail.com" },
      createdAt: "2023-10-15T12:00:00Z",
      total: 110.5,
      subtotal: 115.5,
      tax: 5,
      status: "pending",
      products: [],
    },
    {
      _id: "lwpanncfdx",
      orderCode: "#hafswzqq",
      customer: { _id: "mmxsfww", fullName: "amir", email: "amir@gmail.com" },
      createdAt: "2023-10-08T12:00:00Z",
      total: 98.9,
      subtotal: 100.0,
      tax: 2.1,
      status: "cancelled",
      products: [],
    },
    {
      _id: "poidyyys",
      orderCode: "#xxmztsd",
      customer: { _id: "llaeqcfds", fullName: "ali", email: "ali@gmail.com" },
      createdAt: "2023-10-19T12:00:00Z",
      total: 95.0,
      subtotal: 107.5,
      tax: 12.5,
      status: "shipping",
      products: [],
    },
  ];

  return (
    <DataTable
      tableData={fakeOrders}
      dataColumnsDef={orderColumns}
      filterFns={{ emailFilter, dateRangeFilter }}
    />
  );
};

export default OrdersTable;
